stages:
  - build
  - test

before_script:
  - nuget restore

cache:
 key: "$CI_PIPELINE_ID"
 untracked: true

build:
 stage: build
 script:
    - msbuild ServerLibrary.sln

test_JMAInformation:
 stage: test
 script:
    - msbuild ServerLibrary.sln
    - nunit-console TestJMAInformation/bin/Debug/TestJMAInformation.dll
